homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 97
  unit_system: metric
  time_zone: Europe/Warsaw
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

zone:
  name: work
  icon: mdi:domain
  latitude: 52.1344
  longitude: 21.0586

zone 2:
  name: work
  icon: mdi:domain
  latitude: 52.2316
  longitude: 21.0013

zone 3:
  name: work
  icon: mdi:domain
  latitude: 51.7539
  longitude: 19.4559

frontend:
  javascript_version: auto
  themes:
    red:
      paper-item-icon-color: red
    grey:
      paper-item-icon-color: '#969696'
      paper-item-icon-active-color: '#44739e'

frontend_custom:

customizer: !include customizer.yaml

map:

http:
  api_password: !secret api_password
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  base_url: !secret http_base_url

recorder: !include recorder.yaml

logger: !include logger.yaml

history: !include history.yaml


logbook:
  include:
    entities:
      - device_tracker.agnieszka
      - device_tracker.emil
      - device_tracker.grazyna
      - device_tracker.jerzy
      - group.peoples
      - sensor.edyta_presence
      - sensor.maciek_presence

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_select: !include input_select.yaml
shell_command: !include shell_command.yaml
device_tracker: !include device_tracker.yaml
media_player: !include media_player.yaml
switch: !include switches.yaml
light: !include lights.yaml

sun:

config:

discovery:
  ignore:
    - denonavr
    - harmony
    - yeelight

zeroconf:

ios:

zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_network_key
  device_config: !include zwave_device_config.yaml
  debug: true

mqtt:
  broker: !secret mqtt_broker_ip
  port: !secret mqtt_broker_port
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

xiaomi_aqara:
  gateways:
    mac: !secret migateway_mac
    key: !secret migateway_key

notify:
  - platform: html5
    name: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id
  - platform: nfandroidtv
    name: androidtv
    host: !secret androidtv_hostname

input_boolean: !include input_boolean.yaml

input_number:
  gaming_end_hours:
    min: 0
    max: 23
    step: 1
  gaming_end_minutes:
    min: 0
    max: 59
    step: 1

remote:
  - platform: harmony
    name: Salon
    host: !secret harmonyhub_hostname

history_graph: !include history_graphs.yaml

python_script:

emulated_hue: !include emulated_hue.yaml

homekit: !include homekit.yaml
