- platform: yeelight
  devices:
    192.168.2.245:
      name: bulb salon 1
      transition: 500
      save_on_change: false
      use_music_mode: false
    192.168.2.250:
      name: bulb salon 2
      transition: 500
      save_on_change: false
      use_music_mode: false
    192.168.2.220:
      name: lightstrip sypialnia
      transition: 500
      save_on_change: false
      use_music_mode: false
    192.168.2.225:
      name: lightstrip antek
      transition: 500
      save_on_change: false
      use_music_mode: false

- platform: group
  name: Bulbs Salon
  entities:
    - light.bulb_salon_1
    - light.bulb_salon_2

- platform: mqtt
  name: "Lamp Salon"
  command_topic: "homeassistant/light/lamp-salon/cmnd/power"
  state_topic: "homeassistant/light/lamp-salon/stat/POWER"
  availability_topic: "homeassistant/light/lamp-salon/tele/LWT"
  payload_available: "Aktywny"
  payload_not_available: "Nieaktywny"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 1
  retain: true

- platform: mqtt
  name: "LEDs Przedpokoj"
  command_topic: "homeassistant/light/leds-przedpokoj/cmnd/power"
  state_topic: "homeassistant/light/leds-przedpokoj/stat/POWER"
  availability_topic: "homeassistant/light/leds-przedpokoj/tele/LWT"
  payload_available: "Aktywny"
  payload_not_available: "Nieaktywny"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 1
  retain: true
