- platform: denonavr
  host: !secret denon_hostname
  name: 'Denon'
  timeout: 3
- platform: ps4
  host: !secret playstation_ip
#  credentials_filename: '/home/homeassistant/.homeassistant/.ps4-wake.credentials.json'
  local_store: games
  name: 'PlayStation'
#- platform: dunehd
#  host: !secret dune_hostname
#  name: Dune
#- platform: spotify
#  client_id: !secret spotify_client_id
#  client_secret: !secret spotify_client_secret
#  cache_path: /home/homeassistant/.homeassistant/.spotify-token-cache
#  aliases:
#    0267cda31c46ce6ea8e82dc65cd44ca68312249d: 'Gabinet'
#    d21e573cdb9bd1b7576712f4d73862c355997e74: 'Salon'
#- platform: cast
#  host: !secret androidtv_hostname
