- platform: wake_on_lan
  name: stacjonarny
  host: !secret desktop_hostname
  mac_address: !secret desktop_mac_address
  broadcast_address: 255.255.255.255
  turn_off:
    service:
      shell_command.stacjonarny_off

- platform: flux
  lights: light.bulbs_salon
  name: Flux
  start_colortemp: 4400
  sunset_colortemp: 3800
  stop_colortemp: 3200
  mode: mired
  brightness: 255

- platform: template
  switches:
    denon:
      friendly_name: Amplituner
      value_template: >-
        {% if is_state('media_player.denon', 'on')
           or is_state('media_player.denon', 'playing') %}
          on
        {% elif is_state('media_player.denon', 'off') %}
          off
        {% else %}
          unknown
        {% endif %}
      turn_on:
        service: media_player.turn_on
        entity_id: media_player.denon
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.denon
    playstation:
      friendly_name: PlayStation
      value_template: >-
        {% if is_state('media_player.playstation', 'on')
           or is_state('media_player.playstation', 'playing')
           or is_state('media_player.playstation', 'idle') %}
          on
        {% elif is_state('media_player.playstation', 'off') %}
          off
        {% else %}
          unknown
        {% endif %}
      turn_on:
        service: media_player.turn_on
        entity_id: media_player.playstation
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.playstation
